{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.9.2)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module BoltManagerService_Client(setEnvironmentVar,signal) where
import qualified Data.IORef as R
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


import Bolt_Types
import BoltManagerService
seqid = R.newIORef 0
setEnvironmentVar (ip,op) arg_name arg_value = do
  send_setEnvironmentVar op arg_name arg_value
  recv_setEnvironmentVar ip
send_setEnvironmentVar op arg_name arg_value = do
  seq <- seqid
  seqn <- R.readIORef seq
  T.writeMessageBegin op ("setEnvironmentVar", T.M_CALL, seqn)
  write_SetEnvironmentVar_args op (SetEnvironmentVar_args{setEnvironmentVar_args_name=arg_name,setEnvironmentVar_args_value=arg_value})
  T.writeMessageEnd op
  T.tFlush (T.getTransport op)
recv_setEnvironmentVar ip = do
  (fname, mtype, rseqid) <- T.readMessageBegin ip
  M.when (mtype == T.M_EXCEPTION) $ do { exn <- T.readAppExn ip ; T.readMessageEnd ip ; X.throw exn }
  res <- read_SetEnvironmentVar_result ip
  T.readMessageEnd ip
  P.maybe (P.return ()) X.throw (setEnvironmentVar_result_e res)
  P.return ()
signal (ip,op) arg_topologyId arg_s = do
  send_signal op arg_topologyId arg_s
  recv_signal ip
send_signal op arg_topologyId arg_s = do
  seq <- seqid
  seqn <- R.readIORef seq
  T.writeMessageBegin op ("signal", T.M_CALL, seqn)
  write_Signal_args op (Signal_args{signal_args_topologyId=arg_topologyId,signal_args_s=arg_s})
  T.writeMessageEnd op
  T.tFlush (T.getTransport op)
recv_signal ip = do
  (fname, mtype, rseqid) <- T.readMessageBegin ip
  M.when (mtype == T.M_EXCEPTION) $ do { exn <- T.readAppExn ip ; T.readMessageEnd ip ; X.throw exn }
  res <- read_Signal_result ip
  T.readMessageEnd ip
  P.maybe (P.return ()) X.throw (signal_result_e res)
  P.return ()
